[package]
name = "data-plane"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14.4", features = ["server","http1","http2","tcp","stream","client"] }
tokio = { version = "1.18.0", features = ["net", "macros", "rt", "rt-multi-thread", "io-util", "time"] }
memsec = { version = ">=0.5", default-features = false }
openssl = { version = "0.10.36", features = ["vendored"] }
aws-nitro-enclaves-nsm-api = "0.2.1"
lazy_static = "1.4.0"
async-trait = "0.1.56"
thiserror = "1.0"
bytes = "1"
dns-message-parser = { version = "*", optional = true }
ttl_cache = { version = "*", optional = true }
tokio-rustls = { version = "0.23.4", optional = true }
rustls-pemfile = { version = "1.0.0", optional = true }
tokio-vsock = { version = "0.3.2", optional = true } 


[features]
default = []
local-cert = [] # added to let us compile out any references to local certs
tls = ["dep:tokio-rustls","dep:rustls-pemfile"]
local-tls = ["tls","local-cert"]
network_egress = ["dep:dns-message-parser","dep:ttl_cache"]
enclave = ["dep:tokio-vsock", "network_egress"]
not_enclave = ["network_egress", "tls", "network_egress", "local-tls"]