on:
  push:
    paths:
      - control-plane/**
      - .github/workflows/lint-and-test-control-plane.yml
name: Lint and Test
jobs:
  clippy_check_control_plane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Compile project feature -enclave
        run: cargo build --features enclave -p control-plane 
      - name: Compile project feature -not_enclave
        run: cargo build --features not_enclave -p control-plane 
      - name: Test project
        run: cargo test -p control-plane
      - name: Format project
        run: cargo fmt --check
